; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[common]
framework = arduino
monitor_speed = 115200
lib_deps =
	sparkfun/SparkFun Indoor Air Quality Sensor - ENS160@^1.1.0
	adafruit/Adafruit AHTX0@^2.0.5
	adafruit/Adafruit ILI9341@^1.6.0
	adafruit/Adafruit GFX Library@^1.12.1
	adafruit/Adafruit BusIO@^1.17.4

; ESP32-C3 Pro Mini environment monitor
[env:esp32-c3-envmonitor]
platform = espressif32
board = esp32-c3-devkitm-1
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
build_flags =
	-DBOARD_C3_PRO_MINI
lib_deps =
	${common.lib_deps}
